[package]
name = "game_of_life"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.6"
rand = "0.8"
glam = { version = "0.15", features = ["mint"] }
mint = "0.5"

[profile.dev]
opt-level = 1